"use client";

import React from 'react';
import { Report } from '../lib/types';
import { Download, FileText, Music, BarChart3, Clock, Tag } from 'lucide-react';

interface ReportViewerProps {
  report: Report;
}

export default function ReportViewer({ report }: ReportViewerProps) {
  const { topic, industry, depth, content, docx_url, pdf_url, audio_url, created_at } = report;

  const downloadLinks = [
    { label: 'Word (DOCX)', url: docx_url, icon: FileText, color: 'text-blue-600', bg: 'bg-blue-50' },
    { label: 'PDF', url: pdf_url, icon: Download, color: 'text-red-600', bg: 'bg-red-50' },
    { label: '音声サマリー (MP3)', url: audio_url, icon: Music, color: 'text-green-600', bg: 'bg-green-50' },
  ].filter(link => link.url);

  return (
    <div className="bg-white rounded-2xl shadow-xl overflow-hidden border border-gray-100 animate-in fade-in slide-in-from-bottom-4 duration-700">
      {/* Header Info */}
      <div className="bg-slate-900 p-8 text-white">
        <div className="flex flex-wrap gap-3 mb-4">
          <span className="flex items-center gap-1.5 px-3 py-1 bg-white/10 rounded-full text-xs font-medium backdrop-blur-sm">
            <Tag size={14} />
            {industry || '全業界'}
          </span>
          <span className="flex items-center gap-1.5 px-3 py-1 bg-white/10 rounded-full text-xs font-medium backdrop-blur-sm capitalize">
            <Clock size={14} />
            {depth}
          </span>
        </div>
        <h1 className="text-3xl font-bold tracking-tight mb-2 leading-tight">
          {topic}
        </h1>
        <p className="text-slate-400 text-sm">
          作成日: {new Date(created_at).toLocaleDateString('ja-JP')}
        </p>
      </div>

      {/* Downloads Bar */}
      {downloadLinks.length > 0 && (
        <div className="bg-slate-50 border-b border-gray-200 px-8 py-4 flex flex-wrap gap-4">
          {downloadLinks.map((link) => (
            <a
              key={link.label}
              href={link.url!}
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-2 px-4 py-2 bg-white rounded-lg border border-gray-200 shadow-sm hover:shadow-md hover:border-indigo-300 transition-all group"
            >
              <link.icon className={`${link.color} transition-transform group-hover:scale-110`} size={18} />
              <span className="text-sm font-semibold text-gray-700">{link.label}</span>
            </a>
          ))}
        </div>
      )}

      {/* Content Area */}
      <div className="p-8 lg:p-12 prose prose-slate max-w-none">
        {content ? (
          <div className="whitespace-pre-wrap font-sans text-gray-800 leading-relaxed">
            {/* 
              Normally we'd use react-markdown here. 
              Since it's a generated Japanese report with markdown headers, 
              we'll do a simple rendering for now.
            */}
            {content.split('\n').map((line, i) => {
              if (line.startsWith('# ')) return <h1 key={i} className="text-3xl font-bold mt-8 mb-4 border-b pb-2 text-indigo-900">{line.substring(2)}</h1>;
              if (line.startsWith('## ')) return <h2 key={i} className="text-2xl font-bold mt-8 mb-4 text-indigo-800">{line.substring(3)}</h2>;
              if (line.startsWith('### ')) return <h3 key={i} className="text-xl font-bold mt-6 mb-3 text-indigo-700">{line.substring(4)}</h3>;
              if (line.startsWith('- ') || line.startsWith('* ')) return <li key={i} className="ml-4 list-disc mb-1">{line.substring(2)}</li>;
              return <p key={i} className="mb-4">{line}</p>;
            })}
          </div>
        ) : (
          <div className="flex flex-col items-center justify-center py-20 text-gray-400">
            <BarChart3 size={48} className="mb-4 opacity-20" />
            <p>レポート内容がありません</p>
          </div>
        )}
      </div>

      {/* Footer */}
      <div className="bg-gray-50 p-6 border-t border-gray-100 flex justify-between items-center text-xs text-gray-400">
        <span>© 2026 IntelliDX - Generated by Google Gemini</span>
        <span>ID: {report.id}</span>
      </div>
    </div>
  );
}
